spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-dll: true

spring.datasource:
  driver_class_name: com.mysql.cj.jdbc.Driver
  url: "jdbc:mysql://localhost:3306/CarAdsDB?allowPublicKeyRetrieval=true&useSSL=false"
  username: "root"
  password: "root"
